name: CI/CD Pipeline for EKS Services

on:
  push:
    branches:
      - main   # Trigger workflow on push to main branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # 🔑 Docker Hub login
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 🐳 Build & push COE API image
    - name: Build and push COE API
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/coe-api:latest ./COE_Api
        docker push ${{ secrets.DOCKER_USERNAME }}/coe-api:latest

    # 🐳 Build & push Incubation Backend image
    - name: Build and push Incubation Backend
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/coe-backend:latest ./Incubation_Backend
        docker push ${{ secrets.DOCKER_USERNAME }}/coe-backend:latest

    # 🐳 Build & push Project Management Service
    - name: Build and push Project Management Service
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/project-service:latest ./Project-Management-ims
        docker push ${{ secrets.DOCKER_USERNAME }}/project-service:latest

    # 🐳 Build & push Student Service
    - name: Build and push Student Service
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/student-service:latest ./student_management
        docker push ${{ secrets.DOCKER_USERNAME }}/student-service:latest

    # ☁️ AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # 🔗 Update kubeconfig for EKS
    - name: Update kubeconfig
      run: aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }}

    # 🚀 Deploy services to Kubernetes
    - name: Deploy COE Service (API + Backend)
      run: kubectl apply -f kubernetes/coe.yaml

    - name: Deploy Project Service
      run: kubectl apply -f kubernetes/project.yaml

    - name: Deploy Student Service
      run: kubectl apply -f kubernetes/student.yaml
